apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-koa2
  labels:
    app: hello-world-koa2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-koa2
  template:
    metadata:
      labels:
        app: hello-world-koa2
    spec:
      containers:
      - name: hello-world-koa2
        image: gcr.io/${PROJECT_ID}/hello-world-koa2:$TAG_NAME
        ports:
        - containerPort: 3000
