steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ "build", "-t", "gcr.io/$PROJECT_ID/hello-world-$BRANCH_NAME:$REVISION_ID", "." ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "gcr.io/$PROJECT_ID/hello-world-$BRANCH_NAME:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta 
  - compute 
  - instances 
  - update-container 
  - hello-world-$BRANCH_NAME-vm-1 
  - --zone=us-central1-a 
  - --container-image=gcr.io/$PROJECT_ID/hello-world-$BRANCH_NAME:$REVISION_ID

